### ISSUE TITLE
sampleapp can not run

### ISSUE THREAD

**Issue by holywend** [guardianproject/tor-android#87]
I am trying out tor on android, since im new and got not sure where to start, so I go for the sampleapp, but it does not run as I expected

Gradle sync issue

![image](https://user-images.githubusercontent.com/20583849/194902671-30b3569b-fe39-473e-81ec-21bb8f1ed3e9.png)

then I solve it with comment out the gradle-wrapper.properties

`#distributionSha256Sum=336b6898b491f6334502d8074a6b8c2d73ed83b92123106bd4bf837f04111043`

but then when I sync and run it again now its showing blank webView

![image](https://user-images.githubusercontent.com/20583849/194903287-05178232-d2d1-4aee-a1d5-6bcda40b7605.png)

and got this on the Run terminal

![image](https://user-images.githubusercontent.com/20583849/194903451-793136f6-3191-4b43-97b2-dda94cd302be.png)

```
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 340)
W/GmsClient: IGmsServiceBroker.getService failed
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:584)
        at rF.b(chromium-TrichromeWebViewGoogle6432.apk-stable-495157434:288)
        at com.google.android.gms.common.internal.BaseGmsClient.p(chromium-TrichromeWebViewGoogle6432.apk-stable-495157434:53)
        at WB.run(chromium-TrichromeWebViewGoogle6432.apk-stable-495157434:1849)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at Bq0.dispatchMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-495157434:223)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

any idea what might cause this? and how to fix?

**Comment by bitmold** [comment]
Sorry this wasn't running then. Closing because it runs now.
<img width="296" alt="Screenshot 2024-06-28 at 10 06 24 AM" src="https://github.com/guardianproject/tor-android/assets/22125581/5631c731-7163-4ade-b521-6fbc7f5e6ccf">
